### ISSUE TITLE
Support of Eyeriss-V2 architecture

### ISSUE THREAD

**Issue by morainer** [Accelergy-Project/accelergy#15]
Hi,
Thanks for releasing such useful tools.
But it seems that the simple Mesh XY-NOC cannot support the implementation of the EyerissV2 architecture.
Could you add the [Eyeriss-V2](https://arxiv.org/pdf/1807.07928.pdf) architecture definition?

Thanks.

**Comment by tanner-andrulis** [comment]
Accelergy no longer contains Accelergy definitions. This would be a Q for the Timeloop team. Thanks!
