### ISSUE TITLE
A Qeustion about Idle energy consumption equation

### ISSUE THREAD

**Issue by cocojk** [Accelergy-Project/accelergy#17]
I've read the accelergy cacti energy calculation equation in accelergy-cacti-plug-in/cacti_wrapper.py

In line 224-227, the actual idle energy (the total leakage energy consumption) is obtained by parsing the cacti output. 
In this equation, is there any reason for multiplying 'Random cycle time'?

224                     standby_power_in_w = float(row[cacti_entry]) * 10 ** -3  # mW -> W
225                     idle_energy_per_bank_in_j = standby_power_in_w * float(row[' Random cycle time (ns)']) * 10 ** -9
226                     idle_energy_per_bank_in_pj = idle_energy_per_bank_in_j * 10 ** 12
227                     energy = idle_energy_per_bank_in_pj * n_banks

**Comment by tanner-andrulis** [comment]
This is a heuristic used as a proxy for the latency. It will be replaced with a more rigorous solution in a coming update.

Thanks for the interest!
