### ISSUE TITLE
Outdated Example

### ISSUE THREAD

**Issue by Arash1381-y** [Accelergy-Project/accelergy#21]
The reference output and v 0.4 Accelergy are not similar. Could you please update the examples in this repository to match the v 0.4 version style? I haven't been able to find any specific resources for the new syntax and a more detailed change list. It would be greatly appreciated if you could add them.

**Comment by tanner-andrulis** [comment]
Done. Reference outputs have been migrated to https://github.com/Accelergy-Project/timeloop-accelergy-exercises. Thank you.
