### ISSUE TITLE
Accuracy for table-based plugin not updating

### ISSUE THREAD

**Issue by vkb27** [Accelergy-Project/accelergy#22]
In `timeloop-accelergy/accelergy-timeloop-infrastructure/src/accelergy-table-based-plug-ins/set_of_table_templates/test.table.yaml` I have changed the accuracy to 80 so these values get precedence but even after running `pip install .` in accelergy-table-based-plug-ins directory (tried running pip install . in accelergy directory too) the value in accelergy log is not changing.
Am i missing a step here? 

> 2023-11-17 00:49:38 DEBUG       Why plug-ins did not estimate:
> 2023-11-17 00:49:38 DEBUG       | Aladdin_table with accuracy 70% estimating accuracy: No messages found.
> 2023-11-17 00:49:38 DEBUG       | dummy_table with accuracy 1% estimating accuracy: No messages found.
> 2023-11-17 00:49:38 DEBUG       | table-based-plug-ins with accuracy 0% estimating accuracy: Accuracy is 0%. Not supported.
> 2023-11-17 00:49:38 DEBUG       | CACTI with accuracy 0% estimating accuracy: Class name wire not supported. Supported classes: ['SRAM', 'cache', 'DRAM']

**Comment by tanner-andrulis** [comment]
The table-based plug-in returns zero accuracy when it doesn't recognize a component. It is likely that the component being queried is not in any installed accelergy-table-based-plug-in tables. A few things to check:

- Does the component being queried match a table entry?
- Is the table listed in ~/.config/accelergy/accelergy_config.yaml ?

Let me know if either of those are your issue!
