### ISSUE TITLE
Query on using Timeloop and Accelergy 

### ISSUE THREAD

**Issue by Yukiona1996** [Accelergy-Project/accelergy#23]
Hi,

Just wanted to check in if there's a way for us to load the weight of pre-trained models onto one of the yaml files and use them to perform the necessary analysis on the architecture and mapping?

If yes, could you please redirect me to the relevant documents?

Thanks!

**Comment by tanner-andrulis** [comment]
https://github.com/Accelergy-Project/timeloop-accelergy-exercises/issues/36
