### ISSUE TITLE
Support for 3D CNN

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [Accelergy-Project/accelergy#8]
Hi,

Do you have some support for 3D CNNs in accelergy?

thanks

**Comment by nellie-wu** [comment]
Accelergy is only responsible for energy estimation of the components in the architecture, not the workload. If you are using timeloop-accelergy infrastructure, timeloop is the tool that takes in the the workload shapes, which are directly related to the dimension of your input DNN model.

An example of 3D conv specification for Timeloop can be found here: https://github.com/NVlabs/timeloop/issues/64

**Comment by Diksha-Moolchandani** [comment]
Thanks
